# Generated by Django 4.2.16 on 2024-11-27 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızıl Elma', 'Kızıl Elma')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Kanat', 'Kanat'), ('Gövde', 'Gövde'), ('Kuyruk', 'Kuyruk'), ('Aviyonik', 'Aviyonik'), ('Montaj', 'Montaj')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Kullanım Tarihi')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                ('aircraft_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_inventories', to='api.aircraftinventory')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.team'),
        ),
        migrations.AddField(
            model_name='aircraftinventory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_inventories', to='api.team'),
        ),
    ]
